# coding: utf-8

"""
    OpenApi

     ## ![N|Solid](https://duett.no/wp-content/uploads/2018/10/cropped-Duett-favicon-32x32.png)  _How to take the Duett api in use_  To be able to use the API, you must have an interaction key and a client key.  Eksample curl: ```swift    curl -X 'GET' \\   'https://api.duett.no/article/v1 \\   -H 'accept: application/json' \\   -H 'X-Api-Integration-Key: 89ff1c42-9d90-435a-8a94-20207bc06e1a' \\   -H 'X-Api-Client-Key: 7896feb3-aaa2-4fd2-aaa2-c69de5fd1e5f' ``` ##### [Metode description][1] ##### [Filtering data in openApi][2]   ### Use a code generator as to auto-generate api client:  ##### [NSwagStudio](https://github.com/RicoSuter/NSwag/wiki/NSwagStudio) ##### [Visual studio add-in](https://marketplace.visualstudio.com/items?itemName=ChristianResmaHelle.ApiClientCodeGenerator) \\ ##### [Online code generator for many languages and versions](https://github.com/swagger-api/swagger-codegen)  *** [1]: ../metods-help.html [2]: ../query-help.html  # noqa: E501

    OpenAPI spec version: 1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class HourRegistrationDocumentCreate(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'file_name': 'str',
        'file_data': 'str',
        'hour_registration_id': 'int'
    }

    attribute_map = {
        'file_name': 'fileName',
        'file_data': 'fileData',
        'hour_registration_id': 'hourRegistrationId'
    }

    def __init__(self, file_name=None, file_data=None, hour_registration_id=None):  # noqa: E501
        """HourRegistrationDocumentCreate - a model defined in Swagger"""  # noqa: E501
        self._file_name = None
        self._file_data = None
        self._hour_registration_id = None
        self.discriminator = None
        self.file_name = file_name
        self.file_data = file_data
        self.hour_registration_id = hour_registration_id

    @property
    def file_name(self):
        """Gets the file_name of this HourRegistrationDocumentCreate.  # noqa: E501


        :return: The file_name of this HourRegistrationDocumentCreate.  # noqa: E501
        :rtype: str
        """
        return self._file_name

    @file_name.setter
    def file_name(self, file_name):
        """Sets the file_name of this HourRegistrationDocumentCreate.


        :param file_name: The file_name of this HourRegistrationDocumentCreate.  # noqa: E501
        :type: str
        """
        if file_name is None:
            raise ValueError("Invalid value for `file_name`, must not be `None`")  # noqa: E501

        self._file_name = file_name

    @property
    def file_data(self):
        """Gets the file_data of this HourRegistrationDocumentCreate.  # noqa: E501


        :return: The file_data of this HourRegistrationDocumentCreate.  # noqa: E501
        :rtype: str
        """
        return self._file_data

    @file_data.setter
    def file_data(self, file_data):
        """Sets the file_data of this HourRegistrationDocumentCreate.


        :param file_data: The file_data of this HourRegistrationDocumentCreate.  # noqa: E501
        :type: str
        """
        if file_data is None:
            raise ValueError("Invalid value for `file_data`, must not be `None`")  # noqa: E501

        self._file_data = file_data

    @property
    def hour_registration_id(self):
        """Gets the hour_registration_id of this HourRegistrationDocumentCreate.  # noqa: E501


        :return: The hour_registration_id of this HourRegistrationDocumentCreate.  # noqa: E501
        :rtype: int
        """
        return self._hour_registration_id

    @hour_registration_id.setter
    def hour_registration_id(self, hour_registration_id):
        """Sets the hour_registration_id of this HourRegistrationDocumentCreate.


        :param hour_registration_id: The hour_registration_id of this HourRegistrationDocumentCreate.  # noqa: E501
        :type: int
        """
        if hour_registration_id is None:
            raise ValueError("Invalid value for `hour_registration_id`, must not be `None`")  # noqa: E501

        self._hour_registration_id = hour_registration_id

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(HourRegistrationDocumentCreate, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, HourRegistrationDocumentCreate):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
