/* 
 * OpenApi
 *
 *  ## ![N|Solid](https://duett.no/wp-content/uploads/2018/10/cropped-Duett-favicon-32x32.png)  _How to take the Duett api in use_  To be able to use the API, you must have an interaction key and a client key.  Eksample curl: ```swift    curl -X 'GET' \\   'https://api.duett.no/article/v1 \\   -H 'accept: application/json' \\   -H 'X-Api-Integration-Key: 89ff1c42-9d90-435a-8a94-20207bc06e1a' \\   -H 'X-Api-Client-Key: 7896feb3-aaa2-4fd2-aaa2-c69de5fd1e5f' ``` ##### [Metode description][1] ##### [Filtering data in openApi][2]   ### Use a code generator as to auto-generate api client:  ##### [NSwagStudio](https://github.com/RicoSuter/NSwag/wiki/NSwagStudio) ##### [Visual studio add-in](https://marketplace.visualstudio.com/items?itemName=ChristianResmaHelle.ApiClientCodeGenerator) \\ ##### [Online code generator for many languages and versions](https://github.com/swagger-api/swagger-codegen)  *** [1]: ../metods-help.html [2]: ../query-help.html
 *
 * OpenAPI spec version: 1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using RestSharp;
using IO.Swagger.Client;
using IO.Swagger.Model;

namespace IO.Swagger.Api
{
    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
        public interface IHourRegistrationDocumentApi : IApiAccessor
    {
        #region Synchronous Operations
        /// <summary>
        /// Gets an existing HourRegistrationDocument given the specified Id.
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id">The Id to get HourRegistrationDocument for.</param>
        /// <param name="extend">A list of keys on which to extend the Customer, e.g. Orders (not implemented). (optional)</param>
        /// <returns>HourRegistrationDocument</returns>
        HourRegistrationDocument HourRegistrationDocumentV1IdGet (Guid? id, List<string> extend = null);

        /// <summary>
        /// Gets an existing HourRegistrationDocument given the specified Id.
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id">The Id to get HourRegistrationDocument for.</param>
        /// <param name="extend">A list of keys on which to extend the Customer, e.g. Orders (not implemented). (optional)</param>
        /// <returns>ApiResponse of HourRegistrationDocument</returns>
        ApiResponse<HourRegistrationDocument> HourRegistrationDocumentV1IdGetWithHttpInfo (Guid? id, List<string> extend = null);
        /// <summary>
        /// Creates a new HourRegistrationDocument.
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="body">The HourRegistrationDocumentCreate to create a new HourRegistrationDocument from. (optional)</param>
        /// <returns>string</returns>
        string HourRegistrationDocumentV1Post (HourRegistrationDocumentCreate body = null);

        /// <summary>
        /// Creates a new HourRegistrationDocument.
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="body">The HourRegistrationDocumentCreate to create a new HourRegistrationDocument from. (optional)</param>
        /// <returns>ApiResponse of string</returns>
        ApiResponse<string> HourRegistrationDocumentV1PostWithHttpInfo (HourRegistrationDocumentCreate body = null);
        #endregion Synchronous Operations
        #region Asynchronous Operations
        /// <summary>
        /// Gets an existing HourRegistrationDocument given the specified Id.
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id">The Id to get HourRegistrationDocument for.</param>
        /// <param name="extend">A list of keys on which to extend the Customer, e.g. Orders (not implemented). (optional)</param>
        /// <returns>Task of HourRegistrationDocument</returns>
        System.Threading.Tasks.Task<HourRegistrationDocument> HourRegistrationDocumentV1IdGetAsync (Guid? id, List<string> extend = null);

        /// <summary>
        /// Gets an existing HourRegistrationDocument given the specified Id.
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id">The Id to get HourRegistrationDocument for.</param>
        /// <param name="extend">A list of keys on which to extend the Customer, e.g. Orders (not implemented). (optional)</param>
        /// <returns>Task of ApiResponse (HourRegistrationDocument)</returns>
        System.Threading.Tasks.Task<ApiResponse<HourRegistrationDocument>> HourRegistrationDocumentV1IdGetAsyncWithHttpInfo (Guid? id, List<string> extend = null);
        /// <summary>
        /// Creates a new HourRegistrationDocument.
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="body">The HourRegistrationDocumentCreate to create a new HourRegistrationDocument from. (optional)</param>
        /// <returns>Task of string</returns>
        System.Threading.Tasks.Task<string> HourRegistrationDocumentV1PostAsync (HourRegistrationDocumentCreate body = null);

        /// <summary>
        /// Creates a new HourRegistrationDocument.
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="body">The HourRegistrationDocumentCreate to create a new HourRegistrationDocument from. (optional)</param>
        /// <returns>Task of ApiResponse (string)</returns>
        System.Threading.Tasks.Task<ApiResponse<string>> HourRegistrationDocumentV1PostAsyncWithHttpInfo (HourRegistrationDocumentCreate body = null);
        #endregion Asynchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
        public partial class HourRegistrationDocumentApi : IHourRegistrationDocumentApi
    {
        private IO.Swagger.Client.ExceptionFactory _exceptionFactory = (name, response) => null;

        /// <summary>
        /// Initializes a new instance of the <see cref="HourRegistrationDocumentApi"/> class.
        /// </summary>
        /// <returns></returns>
        public HourRegistrationDocumentApi(String basePath)
        {
            this.Configuration = new IO.Swagger.Client.Configuration { BasePath = basePath };

            ExceptionFactory = IO.Swagger.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="HourRegistrationDocumentApi"/> class
        /// </summary>
        /// <returns></returns>
        public HourRegistrationDocumentApi()
        {
            this.Configuration = IO.Swagger.Client.Configuration.Default;

            ExceptionFactory = IO.Swagger.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="HourRegistrationDocumentApi"/> class
        /// using Configuration object
        /// </summary>
        /// <param name="configuration">An instance of Configuration</param>
        /// <returns></returns>
        public HourRegistrationDocumentApi(IO.Swagger.Client.Configuration configuration = null)
        {
            if (configuration == null) // use the default one in Configuration
                this.Configuration = IO.Swagger.Client.Configuration.Default;
            else
                this.Configuration = configuration;

            ExceptionFactory = IO.Swagger.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Gets the base path of the API client.
        /// </summary>
        /// <value>The base path</value>
        public String GetBasePath()
        {
            return this.Configuration.ApiClient.RestClient.BaseUrl.ToString();
        }

        /// <summary>
        /// Sets the base path of the API client.
        /// </summary>
        /// <value>The base path</value>
        [Obsolete("SetBasePath is deprecated, please do 'Configuration.ApiClient = new ApiClient(\"http://new-path\")' instead.")]
        public void SetBasePath(String basePath)
        {
            // do nothing
        }

        /// <summary>
        /// Gets or sets the configuration object
        /// </summary>
        /// <value>An instance of the Configuration</value>
        public IO.Swagger.Client.Configuration Configuration {get; set;}

        /// <summary>
        /// Provides a factory method hook for the creation of exceptions.
        /// </summary>
        public IO.Swagger.Client.ExceptionFactory ExceptionFactory
        {
            get
            {
                if (_exceptionFactory != null && _exceptionFactory.GetInvocationList().Length > 1)
                {
                    throw new InvalidOperationException("Multicast delegate for ExceptionFactory is unsupported.");
                }
                return _exceptionFactory;
            }
            set { _exceptionFactory = value; }
        }

        /// <summary>
        /// Gets the default header.
        /// </summary>
        /// <returns>Dictionary of HTTP header</returns>
        [Obsolete("DefaultHeader is deprecated, please use Configuration.DefaultHeader instead.")]
        public IDictionary<String, String> DefaultHeader()
        {
            return new ReadOnlyDictionary<string, string>(this.Configuration.DefaultHeader);
        }

        /// <summary>
        /// Add default header.
        /// </summary>
        /// <param name="key">Header field name.</param>
        /// <param name="value">Header field value.</param>
        /// <returns></returns>
        [Obsolete("AddDefaultHeader is deprecated, please use Configuration.AddDefaultHeader instead.")]
        public void AddDefaultHeader(string key, string value)
        {
            this.Configuration.AddDefaultHeader(key, value);
        }

        /// <summary>
        /// Gets an existing HourRegistrationDocument given the specified Id. 
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id">The Id to get HourRegistrationDocument for.</param>
        /// <param name="extend">A list of keys on which to extend the Customer, e.g. Orders (not implemented). (optional)</param>
        /// <returns>HourRegistrationDocument</returns>
        public HourRegistrationDocument HourRegistrationDocumentV1IdGet (Guid? id, List<string> extend = null)
        {
             ApiResponse<HourRegistrationDocument> localVarResponse = HourRegistrationDocumentV1IdGetWithHttpInfo(id, extend);
             return localVarResponse.Data;
        }

        /// <summary>
        /// Gets an existing HourRegistrationDocument given the specified Id. 
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id">The Id to get HourRegistrationDocument for.</param>
        /// <param name="extend">A list of keys on which to extend the Customer, e.g. Orders (not implemented). (optional)</param>
        /// <returns>ApiResponse of HourRegistrationDocument</returns>
        public ApiResponse< HourRegistrationDocument > HourRegistrationDocumentV1IdGetWithHttpInfo (Guid? id, List<string> extend = null)
        {
            // verify the required parameter 'id' is set
            if (id == null)
                throw new ApiException(400, "Missing required parameter 'id' when calling HourRegistrationDocumentApi->HourRegistrationDocumentV1IdGet");

            var localVarPath = "/HourRegistrationDocument/v1/{id}";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "text/plain",
                "application/json",
                "text/json"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (id != null) localVarPathParams.Add("id", this.Configuration.ApiClient.ParameterToString(id)); // path parameter
            if (extend != null) localVarQueryParams.AddRange(this.Configuration.ApiClient.ParameterToKeyValuePairs("multi", "extend", extend)); // query parameter
            // authentication (ApiKeyClientAuthentication) required
            if (!String.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("X-Api-Client-Key")))
            {
                localVarHeaderParams["X-Api-Client-Key"] = this.Configuration.GetApiKeyWithPrefix("X-Api-Client-Key");
            }
            // authentication (ApiKeyIntegrationAuthentication) required
            if (!String.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("X-Api-Integration-Key")))
            {
                localVarHeaderParams["X-Api-Integration-Key"] = this.Configuration.GetApiKeyWithPrefix("X-Api-Integration-Key");
            }
            // authentication (UserAuthentication) required
            // bearer required
            if (!String.IsNullOrEmpty(this.Configuration.AccessToken))
            {
                localVarHeaderParams["Authorization"] = "Bearer " + this.Configuration.AccessToken;
            }

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) this.Configuration.ApiClient.CallApi(localVarPath,
                Method.GET, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("HourRegistrationDocumentV1IdGet", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<HourRegistrationDocument>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => string.Join(",", x.Value)),
                (HourRegistrationDocument) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(HourRegistrationDocument)));
        }

        /// <summary>
        /// Gets an existing HourRegistrationDocument given the specified Id. 
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id">The Id to get HourRegistrationDocument for.</param>
        /// <param name="extend">A list of keys on which to extend the Customer, e.g. Orders (not implemented). (optional)</param>
        /// <returns>Task of HourRegistrationDocument</returns>
        public async System.Threading.Tasks.Task<HourRegistrationDocument> HourRegistrationDocumentV1IdGetAsync (Guid? id, List<string> extend = null)
        {
             ApiResponse<HourRegistrationDocument> localVarResponse = await HourRegistrationDocumentV1IdGetAsyncWithHttpInfo(id, extend);
             return localVarResponse.Data;

        }

        /// <summary>
        /// Gets an existing HourRegistrationDocument given the specified Id. 
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id">The Id to get HourRegistrationDocument for.</param>
        /// <param name="extend">A list of keys on which to extend the Customer, e.g. Orders (not implemented). (optional)</param>
        /// <returns>Task of ApiResponse (HourRegistrationDocument)</returns>
        public async System.Threading.Tasks.Task<ApiResponse<HourRegistrationDocument>> HourRegistrationDocumentV1IdGetAsyncWithHttpInfo (Guid? id, List<string> extend = null)
        {
            // verify the required parameter 'id' is set
            if (id == null)
                throw new ApiException(400, "Missing required parameter 'id' when calling HourRegistrationDocumentApi->HourRegistrationDocumentV1IdGet");

            var localVarPath = "/HourRegistrationDocument/v1/{id}";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "text/plain",
                "application/json",
                "text/json"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (id != null) localVarPathParams.Add("id", this.Configuration.ApiClient.ParameterToString(id)); // path parameter
            if (extend != null) localVarQueryParams.AddRange(this.Configuration.ApiClient.ParameterToKeyValuePairs("multi", "extend", extend)); // query parameter
            // authentication (ApiKeyClientAuthentication) required
            if (!String.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("X-Api-Client-Key")))
            {
                localVarHeaderParams["X-Api-Client-Key"] = this.Configuration.GetApiKeyWithPrefix("X-Api-Client-Key");
            }
            // authentication (ApiKeyIntegrationAuthentication) required
            if (!String.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("X-Api-Integration-Key")))
            {
                localVarHeaderParams["X-Api-Integration-Key"] = this.Configuration.GetApiKeyWithPrefix("X-Api-Integration-Key");
            }
            // authentication (UserAuthentication) required
            // bearer required
            if (!String.IsNullOrEmpty(this.Configuration.AccessToken))
            {
                localVarHeaderParams["Authorization"] = "Bearer " + this.Configuration.AccessToken;
            }

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) await this.Configuration.ApiClient.CallApiAsync(localVarPath,
                Method.GET, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("HourRegistrationDocumentV1IdGet", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<HourRegistrationDocument>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => string.Join(",", x.Value)),
                (HourRegistrationDocument) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(HourRegistrationDocument)));
        }

        /// <summary>
        /// Creates a new HourRegistrationDocument. 
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="body">The HourRegistrationDocumentCreate to create a new HourRegistrationDocument from. (optional)</param>
        /// <returns>string</returns>
        public string HourRegistrationDocumentV1Post (HourRegistrationDocumentCreate body = null)
        {
             ApiResponse<string> localVarResponse = HourRegistrationDocumentV1PostWithHttpInfo(body);
             return localVarResponse.Data;
        }

        /// <summary>
        /// Creates a new HourRegistrationDocument. 
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="body">The HourRegistrationDocumentCreate to create a new HourRegistrationDocument from. (optional)</param>
        /// <returns>ApiResponse of string</returns>
        public ApiResponse< string > HourRegistrationDocumentV1PostWithHttpInfo (HourRegistrationDocumentCreate body = null)
        {

            var localVarPath = "/HourRegistrationDocument/v1";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
                "application/json-patch+json", 
                "application/json", 
                "text/json", 
                "application/_*+json"
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "text/plain",
                "application/json",
                "text/json"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (body != null && body.GetType() != typeof(byte[]))
            {
                localVarPostBody = this.Configuration.ApiClient.Serialize(body); // http body (model) parameter
            }
            else
            {
                localVarPostBody = body; // byte array
            }
            // authentication (ApiKeyClientAuthentication) required
            if (!String.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("X-Api-Client-Key")))
            {
                localVarHeaderParams["X-Api-Client-Key"] = this.Configuration.GetApiKeyWithPrefix("X-Api-Client-Key");
            }
            // authentication (ApiKeyIntegrationAuthentication) required
            if (!String.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("X-Api-Integration-Key")))
            {
                localVarHeaderParams["X-Api-Integration-Key"] = this.Configuration.GetApiKeyWithPrefix("X-Api-Integration-Key");
            }
            // authentication (UserAuthentication) required
            // bearer required
            if (!String.IsNullOrEmpty(this.Configuration.AccessToken))
            {
                localVarHeaderParams["Authorization"] = "Bearer " + this.Configuration.AccessToken;
            }

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) this.Configuration.ApiClient.CallApi(localVarPath,
                Method.POST, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("HourRegistrationDocumentV1Post", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<string>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => string.Join(",", x.Value)),
                (string) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(string)));
        }

        /// <summary>
        /// Creates a new HourRegistrationDocument. 
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="body">The HourRegistrationDocumentCreate to create a new HourRegistrationDocument from. (optional)</param>
        /// <returns>Task of string</returns>
        public async System.Threading.Tasks.Task<string> HourRegistrationDocumentV1PostAsync (HourRegistrationDocumentCreate body = null)
        {
             ApiResponse<string> localVarResponse = await HourRegistrationDocumentV1PostAsyncWithHttpInfo(body);
             return localVarResponse.Data;

        }

        /// <summary>
        /// Creates a new HourRegistrationDocument. 
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="body">The HourRegistrationDocumentCreate to create a new HourRegistrationDocument from. (optional)</param>
        /// <returns>Task of ApiResponse (string)</returns>
        public async System.Threading.Tasks.Task<ApiResponse<string>> HourRegistrationDocumentV1PostAsyncWithHttpInfo (HourRegistrationDocumentCreate body = null)
        {

            var localVarPath = "/HourRegistrationDocument/v1";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
                "application/json-patch+json", 
                "application/json", 
                "text/json", 
                "application/_*+json"
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "text/plain",
                "application/json",
                "text/json"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (body != null && body.GetType() != typeof(byte[]))
            {
                localVarPostBody = this.Configuration.ApiClient.Serialize(body); // http body (model) parameter
            }
            else
            {
                localVarPostBody = body; // byte array
            }
            // authentication (ApiKeyClientAuthentication) required
            if (!String.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("X-Api-Client-Key")))
            {
                localVarHeaderParams["X-Api-Client-Key"] = this.Configuration.GetApiKeyWithPrefix("X-Api-Client-Key");
            }
            // authentication (ApiKeyIntegrationAuthentication) required
            if (!String.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("X-Api-Integration-Key")))
            {
                localVarHeaderParams["X-Api-Integration-Key"] = this.Configuration.GetApiKeyWithPrefix("X-Api-Integration-Key");
            }
            // authentication (UserAuthentication) required
            // bearer required
            if (!String.IsNullOrEmpty(this.Configuration.AccessToken))
            {
                localVarHeaderParams["Authorization"] = "Bearer " + this.Configuration.AccessToken;
            }

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) await this.Configuration.ApiClient.CallApiAsync(localVarPath,
                Method.POST, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("HourRegistrationDocumentV1Post", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<string>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => string.Join(",", x.Value)),
                (string) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(string)));
        }

    }
}
